<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131208134649 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player ADD mainplanet VARCHAR(40) DEFAULT NULL, ADD selectedplanet VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player ADD CONSTRAINT FK_85D6F59A4177357F FOREIGN KEY (mainplanet) REFERENCES lolli_gaw_domain_model_planet (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player ADD CONSTRAINT FK_85D6F59AF10EBD62 FOREIGN KEY (selectedplanet) REFERENCES lolli_gaw_domain_model_planet (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_85D6F59A4177357F ON lolli_gaw_domain_model_player (mainplanet)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_85D6F59AF10EBD62 ON lolli_gaw_domain_model_player (selectedplanet)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player DROP FOREIGN KEY FK_85D6F59A4177357F");
		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player DROP FOREIGN KEY FK_85D6F59AF10EBD62");
		$this->addSql("DROP INDEX UNIQ_85D6F59A4177357F ON lolli_gaw_domain_model_player");
		$this->addSql("DROP INDEX UNIQ_85D6F59AF10EBD62 ON lolli_gaw_domain_model_player");
		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player DROP mainplanet, DROP selectedplanet");
	}
}