<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131208172448 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_planet CHANGE structurereadytime structurereadytime BIGINT UNSIGNED NOT NULL, CHANGE iron iron BIGINT UNSIGNED NOT NULL, CHANGE silicon silicon BIGINT UNSIGNED NOT NULL, CHANGE xenon xenon BIGINT UNSIGNED NOT NULL, CHANGE hydrazine hydrazine BIGINT UNSIGNED NOT NULL, CHANGE energy energy BIGINT UNSIGNED NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_planet CHANGE structurereadytime structurereadytime DOUBLE PRECISION NOT NULL, CHANGE iron iron INT NOT NULL, CHANGE silicon silicon INT NOT NULL, CHANGE xenon xenon INT NOT NULL, CHANGE hydrazine hydrazine INT NOT NULL, CHANGE energy energy INT NOT NULL");
	}
}