<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131209121653 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_planet ADD ironmine INT NOT NULL, ADD siliconmine INT NOT NULL, ADD xenonmine INT NOT NULL, ADD hydrazinemine INT NOT NULL, ADD energymine INT NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_planet DROP ironmine, DROP siliconmine, DROP xenonmine, DROP hydrazinemine, DROP energymine");
	}
}