<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131207223356 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE lolli_gaw_domain_model_player (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE lolli_gaw_domain_model_planet (persistence_object_identifier VARCHAR(40) NOT NULL, player VARCHAR(40) DEFAULT NULL, galaxynumber INT NOT NULL, systemnumber INT NOT NULL, planetnumber INT NOT NULL, structureinprogress INT NOT NULL, structurereadytime DOUBLE PRECISION NOT NULL, name VARCHAR(255) NOT NULL, base INT NOT NULL, INDEX IDX_75DCE55A98197A65 (player), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lolli_gaw_domain_model_player ADD CONSTRAINT FK_85D6F59A47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE lolli_gaw_domain_model_planet ADD CONSTRAINT FK_75DCE55A98197A65 FOREIGN KEY (player) REFERENCES lolli_gaw_domain_model_player (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lolli_gaw_domain_model_planet DROP FOREIGN KEY FK_75DCE55A98197A65");
		$this->addSql("DROP TABLE lolli_gaw_domain_model_player");
		$this->addSql("DROP TABLE lolli_gaw_domain_model_planet");
	}
}